// Generated by CoffeeScript 1.6.3
var controllers, onLoad, routes, weppls;

controllers = require("./controllers");

routes = require("./routes");

weppls = exports;

weppls.main = function() {
  var angularModule;
  angularModule = angular.module("app", []);
  controllers.configure(angularModule);
  routes.configure(angularModule);
  return $(function() {
    return onLoad();
  });
};

onLoad = function() {
  return $(".nav.navbar-nav").click(function() {
    return $(".navbar-collapse").collapse("hide");
  });
};

weppls.log = function(message) {
  return console.log("weppls: " + message);
};

weppls.error = function(message) {
  weppls.log(message);
  throw Error(message);
};

weppls.main();
