// Generated by CoffeeScript 1.6.3
var controllers, routes, weppls;

controllers = require("./controllers");

routes = require("./routes");

weppls = exports;

weppls._ = {};

weppls.main = function() {
  weppls.angularModule = angular.module("app", []);
  controllers.configure(weppls.angularModule);
  return routes.configure(weppls.angularModule);
};

weppls.log = function(message) {
  return console.log("weppls: " + message);
};

weppls.error = function(message) {
  weppls.log(message);
  throw Error(message);
};

weppls.main();
