// Generated by CoffeeScript 1.6.3
var cli, help, nopt, path, pkg, weppls, _;

path = require("path");

_ = require("underscore");

nopt = require("nopt");

pkg = require("../package.json");

weppls = require("./weppls");

cli = exports;

cli.main = function(args) {
  var longOpts, opts, parsed, shortOpts, _ref;
  if (args.length === 0) {
    help();
  }
  if ((_ref = args[0]) === "?" || _ref === "-?" || _ref === "--?") {
    help();
  }
  longOpts = {
    output: path,
    verbose: Boolean,
    help: Boolean
  };
  shortOpts = {
    o: "--output",
    v: "--verbose",
    h: "--help"
  };
  parsed = nopt(longOpts, shortOpts, args, 0);
  if (parsed.help) {
    help();
  }
  args = parsed.argv.remain;
  opts = _.pick(parsed, _.keys(longOpts));
  if (args.length === 0) {
    help();
  }
  weppls.run(args[0], opts);
};

help = function() {
  console.log("" + pkg.name + " [options] directory");
  console.log("");
  console.log("directory is a directory of files to weppl-ize");
  console.log("");
  console.log("options:");
  console.log("");
  console.log("-o --output      output directory");
  console.log("-v --verbose     be verbose");
  console.log("");
  console.log("If you don't specify an output directory, an output directory");
  console.log("of <directory>-out willl be used.");
  console.log("");
  console.log("version: " + pkg.version + "; for more info: " + pkg.homepage);
  return process.exit(1);
};

if (require.main === module) {
  cli.main.call(null, process.argv.slice(2));
}
